#!/usr/bin/env python3
"""Compare two reviewers' independent extraction workbooks field by field (charting pilot and formal extraction).

Inputs are the .xlsx files generated by scripts/build_workbooks.py (after the reviewers saved them) or CSV exports
(a directory with one <table>.csv per dictionary table, plus optional pilot_notes.csv and readme_minutes.csv, as
written by the `export` command). Tables, columns, keys, list/count/coded columns and legacy modules are read from
05_extraction/data_dictionary.json through build_workbooks.extraction_fields(), so the comparison follows the same
single source as the workbooks.

Usage:
    python3 scripts/compare_extraction.py compare --a pilot_extraction_B.xlsx --b pilot_extraction_C.xlsx \\
        --label-a B --label-b C --out-dir 05_extraction/pilot_2026-10-05/compare_round1
    python3 scripts/compare_extraction.py export --in pilot_extraction_B.xlsx --out-dir <dir>   # CSV export for git
    python3 scripts/compare_extraction.py selftest                                              # synthetic pair, temp dir only

What is compared
- Rows are aligned per table by primary key (extraction_provenance: by report_id, because the pilot provenance_id
  carries the reviewer label). --align auto (default) falls back to (report_id, n-th row of that report in sheet
  order) when the two files share fewer than half of their primary keys, i.e. when the reviewers numbered their rows
  differently; the method used is reported per table. Rows found in one file only are listed, not scored.
- Every cell of a matched row that is non-empty in at least one file is scored: agree / disagree / only_<A> /
  only_<B>. Values are compared after trimming and collapsing white space; counts as integers; multi-valued ("; ")
  columns as sets. Free text is compared exactly and is reported separately (value_kind = free_text), because
  exact agreement on prose is not expected; read those disagreements, do not count them.
- Reviewer-slot columns (..._A / ..._B, e.g. screening_decision_reviewer_A/_B, extractor_a_b.extractor_A/_B,
  digitizer_A/_B) are paired across files: file A's slot --slot-a column against file B's slot --slot-b column
  (pilot: B uses slot A, C uses slot B). Values typed into the other slot are listed as slot warnings.
- Not scored (listed in the summary): columns that differ by design (provenance_id, extractor_a_b.extractor_A/_B,
  recorded_at, digitizer_A/_B) and, when both inputs are pilot workbooks, the bibliographic reports columns that
  build_workbooks.py --populate-reports pre-filled (identical by construction). Agreement is also given for coded + count cells only (coded_and_counts_only), the judgement
  fields that can agree exactly; identifiers (row keys) and free text are reported but should be read.
- Cells empty in both files are not scored; they are listed per table/field/report in empty_by_both.csv with a
  candidate reason (flagged in pilot_notes as not extractable / as unclear, or unflagged for D to classify).

Outputs (in --out-dir): agreement_summary.json, agreement_by_table.csv, agreement_by_family.csv,
agreement_by_field.csv, disagreements.csv, empty_by_both.csv, row_coverage.csv, minutes_and_questions.csv,
pilot_notes_combined.csv. Agreement figures are descriptive only; pilot data are not results.
"""
from __future__ import annotations

import argparse
import csv
import datetime as _dt
import hashlib
import json
import re
import sys
import tempfile
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import build_workbooks as bw  # noqa: E402  (single source: dictionary parsing and pilot sheet layout)

ROOT = bw.ROOT
ALIGN_BY_REPORT = {'extraction_provenance': 'report_id'}
# Columns that differ between reviewers by design (reviewer identity / event time); listed, never scored.
NOT_SCORED = {('extraction_provenance', 'provenance_id'), ('extraction_provenance', 'extractor_a_b.extractor_A'),
              ('extraction_provenance', 'extractor_a_b.extractor_B'), ('extraction_provenance', 'recorded_at'),
              ('measurements', 'digitizer_A'), ('measurements', 'digitizer_B')}
EXTRA_SHEETS = (bw.PILOT_NOTES_SHEET,)
README_CSV = 'readme_minutes.csv'
# Field families: legacy_61_fields module where the column maps to a legacy field (via build_workbooks); otherwise
# this documented map for the operational fields added after the legacy 61 (unlisted -> "other").
NONLEGACY_FAMILY = {
    'reference_id': 'identity', 'title': 'identity', 'authors': 'identity', 'year': 'identity', 'url': 'identity',
    'version_label': 'identity',
    'screening_decision_reviewer': 'eligibility', 'consensus_screening_decision': 'eligibility',
    'primary_fulltext_exclusion_reason': 'eligibility', 'scope_streams': 'eligibility',
    'author_stated_use': 'author_use_and_window_interpretation',
    'author_window_interpretation': 'author_use_and_window_interpretation',
    'author_window_interpretation_locator': 'author_use_and_window_interpretation',
    'cohort_label': 'population', 'age_range': 'population', 'adult_stratum_separable': 'population',
    'older_adult_subgroup': 'population', 'report_specific_population': 'population', 'age_sex_stratum': 'population',
    'n_aliquots': 'population', 'n_donors': 'population', 'donor_count_basis': 'population',
    'participant_linkage': 'population',
    'group_condition': 'exposure', 'intervention_phase': 'exposure', 'exercise_duration': 'exposure',
    'intensity_metric': 'exposure', 'intensity_value': 'exposure', 'bout_id': 'exposure', 'bout_number': 'exposure',
    'sample_role': 'sampling', 'within_organising_window': 'sampling',
    'assay_platform': 'biomarkers', 'cell_context': 'biomarkers', 'marker_family': 'biomarkers',
    'effect_measure': 'analysis', 'effect_value': 'analysis', 'effect_unit': 'analysis', 'result_direction': 'analysis',
    'record_type': 'candidate_universe', 'assay_universe_id': 'candidate_universe',
    'marker_series_id': 'candidate_universe', 'reported_feature_count': 'candidate_universe',
    'tested_universe': 'candidate_universe', 'feature_': 'candidate_universe', 'candidate_': 'candidate_universe',
    'supplement_': 'candidate_universe', 'result_status': 'candidate_universe',
    'effect_value_source': 'digitization', 'digitiz': 'digitization', 'figure_panel_locator': 'digitization',
    'precision_domain': 'validation', 'evidence_state': 'validation', 'relationship_tags': 'validation',
    'intended_use': 'validation', 'linkage_subtype': 'validation', 'validation_use_subtype': 'validation',
    'validation_split': 'validation',
    'study_label': 'identity', 'registry_ids': 'identity',
    'recorded_at': 'provenance', 'provenance_notes': 'provenance',
}


# ---------------------------------------------------------------------------------------------
# Dictionary
# ---------------------------------------------------------------------------------------------
def load_schema() -> dict:
    src = bw.load_sources()
    tables, *_ = bw.extraction_fields(src)
    schema = {}
    for t, info in tables.items():
        pk = info['spec']['primary_key']
        cols = {}
        names = [m['field'] for m in info['fields']]
        for m in info['fields']:
            f = m['field']
            if m['is_id']:
                kind = 'identifier'
            elif m['is_count']:
                kind = 'count'
            elif m['list_name']:
                kind = 'coded'
            else:
                kind = 'free_text'
            cols[f] = {'kind': kind, 'is_list': m['is_list'], 'family': family_of(f, m), 'is_id': m['is_id']}
        schema[t] = {'pk': pk, 'fields': names, 'cols': cols, 'slots': slot_pairs(names)}
    return {'tables': schema, 'dictionary_sha256': src['dictionary']['sha256']}


def family_of(field: str, meta: dict) -> str:
    if meta['is_id']:
        return 'keys'
    if meta['legacy']:
        return meta['legacy']['module']
    if 'locator' in field and field not in NONLEGACY_FAMILY:
        return 'source_locator'
    if field.endswith('notes'):
        return 'notes'
    base = re.sub(r'_[AB]$', '', field)
    for k, fam in NONLEGACY_FAMILY.items():
        if field == k or base == k or (k.endswith('_') and field.startswith(k)) or (k == 'digitiz' and 'digitiz' in field):
            return fam
    return 'other'


def slot_pairs(names) -> dict:
    """{slot-A column: slot-B column} for columns that differ only by an upper-case A/B token."""
    pairs = {}
    for f in names:
        toks = re.split(r'([_.])', f)
        for i, tok in enumerate(toks):
            if tok == 'A':
                other = ''.join(toks[:i] + ['B'] + toks[i + 1:])
                if other in names:
                    pairs[f] = other
    return pairs


# ---------------------------------------------------------------------------------------------
# Reading
# ---------------------------------------------------------------------------------------------
def norm_cell(v) -> str:
    if v is None:
        return ''
    if isinstance(v, bool):
        return 'TRUE' if v else 'FALSE'
    if isinstance(v, float) and v.is_integer():
        return str(int(v))
    if isinstance(v, (_dt.datetime, _dt.date)):
        return v.isoformat()
    return re.sub(r'\s+', ' ', str(v)).strip()


def read_source(path: Path, schema: dict) -> dict:
    path = Path(path)
    out = {'path': str(path), 'tables': {}, 'notes': [], 'minutes': {}, 'date_finished': '', 'is_pilot': False}
    if path.is_dir():
        files = sorted(path.glob('*.csv'))
        out['sha256'] = {p.name: hashlib.sha256(p.read_bytes()).hexdigest() for p in files}
        for t in list(schema['tables']) + list(EXTRA_SHEETS):
            p = path / f'{t}.csv'
            rows = list(csv.DictReader(p.open(encoding='utf-8-sig'))) if p.exists() else []
            rows = [{k: norm_cell(v) for k, v in r.items()} for r in rows]
            rows = [r for r in rows if any(r.values())]
            if t in EXTRA_SHEETS:
                out['notes'] = rows
            else:
                out['tables'][t] = rows
        p = path / README_CSV
        if p.exists():
            out['is_pilot'] = True
            for r in csv.DictReader(p.open(encoding='utf-8-sig')):
                if r.get('report_id') == '__date_finished__':
                    out['date_finished'] = norm_cell(r.get('minutes'))
                else:
                    out['minutes'][r['report_id']] = {'minutes': norm_cell(r.get('minutes')),
                                                      'questions': norm_cell(r.get('unresolved_questions'))}
        return out
    import openpyxl
    out['sha256'] = {path.name: hashlib.sha256(path.read_bytes()).hexdigest()}
    wb = openpyxl.load_workbook(path, data_only=True)
    for t in list(schema['tables']) + list(EXTRA_SHEETS):
        if t not in wb.sheetnames:
            if t in schema['tables']:
                raise SystemExit(f'{path}: sheet {t} missing')
            continue
        ws = wb[t]
        head = [norm_cell(c.value) for c in ws[1]]
        rows = []
        for row in ws.iter_rows(min_row=2, values_only=True):
            r = {h: norm_cell(v) for h, v in zip(head, row) if h}
            if any(r.values()):
                rows.append(r)
        if t in EXTRA_SHEETS:
            out['notes'] = rows
        else:
            missing = [f for f in schema['tables'][t]['fields'] if f not in head]
            if missing:
                raise SystemExit(f'{path}: sheet {t} lacks columns {missing[:5]} (not generated from this dictionary?)')
            out['tables'][t] = rows
    if 'README' in wb.sheetnames:
        rd = wb['README']
        hdr = next((c.row for c in rd['C'] if c.value == bw.PILOT_MINUTES_HEADER), None)
        if hdr:
            out['is_pilot'] = True
            r = hdr + 1
            while rd.cell(row=r, column=1).value:
                out['minutes'][norm_cell(rd.cell(row=r, column=1).value)] = {
                    'minutes': norm_cell(rd.cell(row=r, column=3).value),
                    'questions': norm_cell(rd.cell(row=r, column=4).value)}
                r += 1
        for c in rd['A']:
            if c.value == bw.PILOT_DATE_LABEL:
                out['date_finished'] = norm_cell(rd.cell(row=c.row, column=2).value)
    return out


def export(path: Path, out_dir: Path, schema: dict) -> list:
    data = read_source(path, schema)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for t, rows in data['tables'].items():
        written.append(write_csv(out_dir / f'{t}.csv', schema['tables'][t]['fields'], rows))
    written.append(write_csv(out_dir / f'{bw.PILOT_NOTES_SHEET}.csv', bw.PILOT_NOTES_COLUMNS, data['notes']))
    mins = [{'report_id': k, 'minutes': v['minutes'], 'unresolved_questions': v['questions']}
            for k, v in data['minutes'].items()]
    if data['date_finished']:
        mins.append({'report_id': '__date_finished__', 'minutes': data['date_finished'], 'unresolved_questions': ''})
    written.append(write_csv(out_dir / README_CSV, ['report_id', 'minutes', 'unresolved_questions'], mins))
    return written


def write_csv(p: Path, cols, rows) -> str:
    with p.open('w', newline='', encoding='utf-8') as f:
        w = csv.DictWriter(f, fieldnames=list(cols), extrasaction='ignore', lineterminator='\n')
        w.writeheader()
        for r in rows:
            w.writerow({c: r.get(c, '') for c in cols})
    return str(p)


# ---------------------------------------------------------------------------------------------
# Comparison
# ---------------------------------------------------------------------------------------------
def norm_value(v: str, meta: dict) -> str:
    if v == '':
        return ''
    if meta['is_list']:
        return '; '.join(sorted({x.strip() for x in v.split(';') if x.strip()}))
    if meta['kind'] == 'count':
        try:
            f = float(v)
            return str(int(f)) if f.is_integer() else str(f)
        except ValueError:
            return v
    return v


def align(rows_a, rows_b, key: str, mode: str):
    """Return (pairs, only_a, only_b, method, duplicates)."""
    def keyed(rows, k):
        d, dup = {}, []
        for r in rows:
            kv = r.get(k, '')
            if kv in d:
                dup.append(kv)
                continue
            d[kv] = r
        return d, dup

    def ordinal(rows):
        seen, d = Counter(), {}
        for r in rows:
            rid = r.get('report_id', '')
            seen[rid] += 1
            d[f'{rid}#{seen[rid]}'] = r
        return d, []

    method = 'key:' + key
    da, dupa = keyed(rows_a, key)
    db, dupb = keyed(rows_b, key)
    if mode == 'ordinal' or (mode == 'auto' and key != 'report_id' and rows_a and rows_b
                             and 'report_id' in rows_a[0]
                             and len(set(da) & set(db)) < 0.5 * min(len(da), len(db))):
        da, dupa = ordinal(rows_a)
        db, dupb = ordinal(rows_b)
        method = 'ordinal:report_id#n'
    keys = list(dict.fromkeys(list(da) + list(db)))
    pairs = [(k, da[k], db[k]) for k in keys if k in da and k in db]
    only_a = [(k, da[k]) for k in keys if k in da and k not in db]
    only_b = [(k, db[k]) for k in keys if k in db and k not in da]
    return pairs, only_a, only_b, method, dupa + dupb


def compare(a: dict, b: dict, schema: dict, la: str, lb: str, slot_a: str, slot_b: str, mode: str = 'auto',
            pair_slots: bool = True) -> dict:
    by_field = defaultdict(Counter)
    meta_of = {}
    disagreements, empty, coverage, slot_warn, tables_out = [], [], [], [], {}
    notes = [dict(n, reviewer=la) for n in a['notes']] + [dict(n, reviewer=lb) for n in b['notes']]
    flagged = defaultdict(set)
    for n in notes:
        for fld in [x.strip() for x in n.get('field', '').split(';') if x.strip()]:
            flagged[(n.get('table', ''), fld, n.get('report_id', ''))].add(n.get('issue_type', '') or 'unspecified')
    # cohorts / study_families carry no report_id: resolve through either reviewer's report_cohort_links
    via = defaultdict(set)
    for src in (a, b):
        for r in src['tables'].get('report_cohort_links', []):
            for k in ('cohort_id', 'study_id'):
                if r.get(k) and r.get('report_id'):
                    via[(k, r[k])].add(r['report_id'])

    def report_of(t, row_a, row_b, key_value):
        for r in (row_a, row_b):
            if r.get('report_id'):
                return r['report_id']
        if t == 'extraction_provenance' or key_value.startswith('PILOT-'):
            return key_value
        k = 'cohort_id' if t == 'cohorts' else ('study_id' if t == 'study_families' else None)
        ids = set()
        for r in (row_a, row_b):
            if k and r.get(k):
                ids |= via[(k, r[k])]
        return '; '.join(sorted(ids))
    skip = set(NOT_SCORED)
    if a['is_pilot'] and b['is_pilot']:      # generator-filled bibliographic cells are identical by construction
        skip |= {('reports', c) for c in bw.PILOT_REPORT_PREFILL}
    for t, S in schema['tables'].items():
        rows_a, rows_b = a['tables'].get(t, []), b['tables'].get(t, [])
        key = ALIGN_BY_REPORT.get(t, S['pk'])
        pairs, only_a, only_b, method, dups = align(rows_a, rows_b, key, mode)
        rids = sorted({r.get('report_id', '') for r in rows_a + rows_b} - {''}) if 'report_id' in S['fields'] else []
        for rid in rids:
            coverage.append({'table': t, 'report_id': rid,
                             f'rows_{la}': sum(1 for r in rows_a if r.get('report_id') == rid),
                             f'rows_{lb}': sum(1 for r in rows_b if r.get('report_id') == rid)})
        for side, lst in ((la, only_a), (lb, only_b)):
            for k, r in lst:
                disagreements.append({'table': t, 'align_key': k, 'report_id': r.get('report_id', ''), 'field': '(row)',
                                      'family': '', 'value_kind': '', 'category': f'row_only_{side}',
                                      f'value_{la}': json.dumps(r, ensure_ascii=False) if side == la else '',
                                      f'value_{lb}': json.dumps(r, ensure_ascii=False) if side == lb else ''})
        # columns to compare
        fields = []
        paired_b = set(S['slots'].values()) if pair_slots else set()
        for f in S['fields']:
            if f in paired_b or (t, f) in skip:
                continue
            if pair_slots and f in S['slots']:
                fields.append((slot_col(f, '<own slot>'), slot_col(f, slot_a), slot_col(f, slot_b), S['cols'][f]))
            else:
                fields.append((f, f, f, S['cols'][f]))
        if pair_slots:
            for f in S['slots']:
                for side, rows, own in ((la, rows_a, slot_a), (lb, rows_b, slot_b)):
                    for other in ('A', 'B'):
                        if other == own:
                            continue
                        col = slot_col(f, other)
                        for r in rows:
                            if r.get(col):
                                slot_warn.append({'table': t, 'reviewer': side, 'column': col,
                                                  'report_id': r.get('report_id', ''), 'value': r[col]})
        tc = Counter()
        for k, ra, rb in pairs:
            rid = report_of(t, ra, rb, k)
            for name, fa, fb, meta in fields:
                if method.startswith('key:') and fa == key:
                    continue
                va, vb = norm_value(ra.get(fa, ''), meta), norm_value(rb.get(fb, ''), meta)
                fid = (t, name)
                meta_of[fid] = meta
                if not va and not vb:
                    by_field[fid]['both_empty'] += 1
                    empty.append((t, name, rid, meta))
                    continue
                cat = 'agree' if va == vb else ('disagree' if va and vb else (f'only_{la}' if va else f'only_{lb}'))
                by_field[fid][cat] += 1
                tc[cat] += 1
                tc[f'{meta["kind"]}:{cat}'] += 1
                if cat != 'agree':
                    disagreements.append({'table': t, 'align_key': k, 'report_id': rid, 'field': name,
                                          'family': meta['family'], 'value_kind': meta['kind'], 'category': cat,
                                          f'value_{la}': ra.get(fa, ''), f'value_{lb}': rb.get(fb, '')})
        tables_out[t] = {'align': method, 'rows': {la: len(rows_a), lb: len(rows_b)}, 'rows_matched': len(pairs),
                         f'rows_only_{la}': len(only_a), f'rows_only_{lb}': len(only_b), 'duplicate_keys': dups,
                         **metrics(tc, la, lb), 'coded_and_counts_only': metrics(non_free_text(tc), la, lb)}
    # empty-by-both: per table/field/report (group rows of the same report)
    grouped = defaultdict(int)
    for t, name, rid, meta in empty:
        grouped[(t, name, rid)] += 1
    empty_rows = []
    for (t, name, rid), n in grouped.items():
        base = name.replace('<own slot>', 'A')
        flags = set()
        for fld in {base, name, name.replace('<own slot>', 'B')}:
            for r in [x.strip() for x in rid.split(';')] + ['']:
                flags |= flagged.get((t, fld, r), set())
        if 'not_extractable_from_text' in flags:
            cand = 'not_extractable_from_text (flagged in pilot_notes)'
        elif flags:
            cand = 'manual_or_dictionary_unclear (flagged in pilot_notes: ' + ', '.join(sorted(flags)) + ')'
        else:
            cand = 'unflagged: D to classify (not extractable from text / manual unclear / not attempted)'
        empty_rows.append({'table': t, 'field': name, 'family': schema['tables'][t]['cols'].get(base, {}).get('family', ''),
                           'report_id': rid, 'matched_rows_both_empty': n, 'candidate_reason': cand})
    # field / family summaries
    field_rows, fam = [], defaultdict(Counter)
    for (t, name), c in by_field.items():
        meta = meta_of[(t, name)]
        field_rows.append({'table': t, 'field': name, 'family': meta['family'], 'value_kind': meta['kind'],
                           **metrics(c, la, lb), 'both_empty': c['both_empty']})
        for k in ('agree', 'disagree', f'only_{la}', f'only_{lb}'):
            fam[meta['family']][k] += c[k]
            if meta['kind'] in ('coded', 'count'):
                fam[meta['family']]['nf:' + k] += c[k]
    fam_rows = [{'family': f, **metrics(c, la, lb), 'coded_and_counts_only': metrics(
        Counter({k[3:]: v for k, v in c.items() if k.startswith('nf:')}), la, lb)} for f, c in sorted(fam.items())]
    total = Counter()
    for r in tables_out.values():
        for k in ('agree', 'disagree', f'only_{la}', f'only_{lb}'):
            total[k] += r[k]
    mins = []
    for rid in sorted(set(a['minutes']) | set(b['minutes'])):
        ma, mb = a['minutes'].get(rid, {}), b['minutes'].get(rid, {})
        mins.append({'report_id': rid, f'minutes_{la}': ma.get('minutes', ''), f'minutes_{lb}': mb.get('minutes', ''),
                     f'unresolved_questions_{la}': ma.get('questions', ''),
                     f'unresolved_questions_{lb}': mb.get('questions', '')})
    return {'tables': tables_out, 'fields': field_rows, 'families': fam_rows, 'overall': metrics(total, la, lb),
            'disagreements': disagreements, 'empty_by_both': empty_rows, 'coverage': coverage,
            'slot_warnings': slot_warn, 'minutes': mins, 'notes': notes,
            'not_scored': sorted(f'{t}.{f}' for t, f in skip),
            'date_finished': {la: a['date_finished'], lb: b['date_finished']}}


def non_free_text(c: Counter) -> Counter:
    """Coded and count cells only (identifiers and free text removed)."""
    out = Counter()
    for k, n in c.items():
        if ':' in k and k.split(':', 1)[0] in ('coded', 'count'):
            out[k.split(':', 1)[1]] += n
    return out


def slot_col(f: str, slot: str) -> str:
    toks = re.split(r'([_.])', f)
    i = max(i for i, tok in enumerate(toks) if tok == 'A')
    return ''.join(toks[:i] + [slot] + toks[i + 1:])


def metrics(c: Counter, la: str, lb: str) -> dict:
    agree, dis, oa, ob = c['agree'], c['disagree'], c[f'only_{la}'], c[f'only_{lb}']
    both, anyf = agree + dis, agree + dis + oa + ob
    return {'cells_compared': anyf, 'agree': agree, 'disagree': dis, f'only_{la}': oa, f'only_{lb}': ob,
            'agreement_both_filled': round(agree / both, 4) if both else None,
            'agreement_any_filled': round(agree / anyf, 4) if anyf else None}


def flat(d: dict) -> dict:
    out = {}
    for k, v in d.items():
        if isinstance(v, dict):
            for k2, v2 in v.items():
                out[f'{k}.{k2}'] = v2
        elif isinstance(v, list):
            out[k] = '; '.join(map(str, v))
        else:
            out[k] = v
    return out


def write_outputs(res: dict, out_dir: Path, info: dict, la: str, lb: str) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)

    def dump(name, rows, cols=None):
        rows = [flat(r) for r in rows]
        cols = cols or list(dict.fromkeys(k for r in rows for k in r)) or ['(none)']
        write_csv(out_dir / name, cols, rows)

    dump('agreement_by_table.csv', [{'table': t, **v} for t, v in res['tables'].items()])
    dump('agreement_by_family.csv', res['families'])
    dump('agreement_by_field.csv', sorted(res['fields'], key=lambda r: (r['table'], r['field'])))
    dump('disagreements.csv', res['disagreements'],
         ['table', 'report_id', 'align_key', 'field', 'family', 'value_kind', 'category', f'value_{la}', f'value_{lb}'])
    dump('empty_by_both.csv', sorted(res['empty_by_both'], key=lambda r: (r['table'], r['field'], r['report_id'])),
         ['table', 'field', 'family', 'report_id', 'matched_rows_both_empty', 'candidate_reason'])
    dump('row_coverage.csv', res['coverage'], ['table', 'report_id', f'rows_{la}', f'rows_{lb}'])
    dump('minutes_and_questions.csv', res['minutes'],
         ['report_id', f'minutes_{la}', f'minutes_{lb}', f'unresolved_questions_{la}', f'unresolved_questions_{lb}'])
    dump('pilot_notes_combined.csv', res['notes'], ['reviewer'] + bw.PILOT_NOTES_COLUMNS)
    cat = Counter(d['category'] for d in res['disagreements'])
    summary = {
        'generated_at_utc': _dt.datetime.now(_dt.timezone.utc).isoformat(timespec='seconds'),
        'generator': 'scripts/compare_extraction.py', **info,
        'status': 'Descriptive agreement between two independent extractions; not results. Free-text exact-match '
                  'agreement is reported but should be read, not scored.',
        'overall': res['overall'], 'disagreement_categories': dict(cat),
        'not_scored_columns': res['not_scored'],
        'tables': res['tables'], 'families': res['families'],
        'empty_by_both': {'cells': sum(r['matched_rows_both_empty'] for r in res['empty_by_both']),
                          'table_field_report_entries': len(res['empty_by_both'])},
        'slot_warnings': res['slot_warnings'], 'date_finished': res['date_finished'],
        'pilot_notes': {la: sum(1 for n in res['notes'] if n['reviewer'] == la),
                        lb: sum(1 for n in res['notes'] if n['reviewer'] == lb)},
        'outputs': sorted(p.name for p in out_dir.glob('*.csv')),
    }
    (out_dir / 'agreement_summary.json').write_text(json.dumps(summary, ensure_ascii=False, indent=2) + '\n')
    return summary


def run_compare(args) -> int:
    schema = load_schema()
    a, b = read_source(args.a, schema), read_source(args.b, schema)
    res = compare(a, b, schema, args.label_a, args.label_b, args.slot_a, args.slot_b, args.align,
                  pair_slots=not args.no_slot_pairing)
    info = {'inputs': {args.label_a: {'path': str(args.a), 'sha256': a['sha256']},
                       args.label_b: {'path': str(args.b), 'sha256': b['sha256']}},
            'slots': {args.label_a: args.slot_a, args.label_b: args.slot_b},
            'dictionary_sha256': schema['dictionary_sha256'], 'align_mode': args.align}
    s = write_outputs(res, args.out_dir, info, args.label_a, args.label_b)
    print(json.dumps({'out_dir': str(args.out_dir), 'overall': s['overall'],
                      'disagreement_categories': s['disagreement_categories'],
                      'empty_by_both': s['empty_by_both'], 'slot_warnings': len(s['slot_warnings'])}, ensure_ascii=False))
    return 0


# ---------------------------------------------------------------------------------------------
# Self-test on a synthetic pair (temporary directory only; no project file is written)
# ---------------------------------------------------------------------------------------------
def selftest() -> int:
    import openpyxl
    schema = load_schema()
    ok, results = True, []

    def check(label, cond):
        nonlocal ok
        results.append({'check': label, 'passed': bool(cond)})
        ok &= bool(cond)

    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        rep_csv = td / 'reports.csv'
        with rep_csv.open('w', newline='', encoding='utf-8') as f:
            w = csv.writer(f)
            w.writerow(['pilot_item_id', 'reference_id', 'title', 'authors', 'year', 'doi', 'pmid', 'url', 'pilot_purpose',
                        'fulltext_source'])
            w.writerow(['pilot_01', 'S01', 'Synthetic report one', 'Doe J', '2020', '10.0000/s01', '1', 'https://x/1', 'p1', 'PMC'])
            w.writerow(['pilot_02', 'S02', 'Synthetic report two', 'Roe R', '2021', '10.0000/s02', '2', 'https://x/2', 'p2', 'PMC'])
        files = {}
        for lab in ('B', 'C'):
            out = td / f'x_{lab}.xlsx'
            rc = bw.main(['--populate-reports', str(rep_csv), '--reviewer-label', lab, '--out', str(out)])
            check(f'generator builds and verifies pilot workbook {lab}', rc == 0)
            files[lab] = out

        def fill(path, data, minutes, notes):
            wb = openpyxl.load_workbook(path)
            for t, rows in data.items():
                ws = wb[t]
                head = [c.value for c in ws[1]]
                if t in ('reports', 'extraction_provenance'):      # pre-filled rows: match on report_id
                    for vals in rows:
                        r = next(c.row for c in ws['B' if t == 'extraction_provenance' else 'A']
                                 if c.value == vals['report_id'])
                        for k, v in vals.items():
                            ws.cell(row=r, column=head.index(k) + 1, value=v)
                    continue
                for i, vals in enumerate(rows, start=2):
                    for k, v in vals.items():
                        ws.cell(row=i, column=head.index(k) + 1, value=v)
            rd = wb['README']
            for c in rd['A']:
                if c.value in minutes:
                    rd.cell(row=c.row, column=3, value=minutes[c.value])
            ws = wb[bw.PILOT_NOTES_SHEET]
            for i, n in enumerate(notes, start=2):
                for k, v in n.items():
                    ws.cell(row=i, column=bw.PILOT_NOTES_COLUMNS.index(k) + 1, value=v)
            wb.save(path)

        r1, r2 = 'PILOT-S01', 'PILOT-S02'
        fill(files['B'], {
            'reports': [{'report_id': r1, 'screening_decision_reviewer_A': 'INCLUDE_A', 'immune_link': 'x; y',
                         'publication_status': 'peer_reviewed_version_of_record', 'reviewer_notes': 'only in B'}],
            'cohorts': [{'cohort_id': 'C-S01-1', 'study_id': 'S-S01-1', 'n_recruited': 12, 'age_range': '20-30'}],
            'report_cohort_links': [{'link_id': 'L-S01-1', 'report_id': r1, 'study_id': 'S-S01-1',
                                     'cohort_id': 'C-S01-1'}],
            'sample_sets': [{'sample_set_id': 'SS-S01-01', 'report_id': r1, 'time_bin': 'pre_exercise_baseline'},
                            {'sample_set_id': 'SS-S01-02', 'report_id': r1, 'time_bin': '0_to_lt30min'}],
            'measurements': [{'measurement_id': 'M-S01-001', 'report_id': r1, 'marker_family': 'mucosal_sIgA'},
                             {'measurement_id': 'M-S01-002', 'report_id': r1, 'marker_family': 'proteome'}],
            'extraction_provenance': [{'report_id': r1, 'extractor_a_b.extractor_A': 'B'}],
        }, {r1: 30, r2: 12.5}, [])
        fill(files['C'], {
            'reports': [{'report_id': r1, 'screening_decision_reviewer_B': 'INCLUDE_A', 'immune_link': 'y; x',
                         'publication_status': 'peer_reviewed_version_of_record',
                         'screening_decision_reviewer_A': 'WRONG_SLOT'}],
            'cohorts': [{'cohort_id': 'C-S01-1', 'study_id': 'S-S01-1', 'n_recruited': '12', 'age_range': '21-30'}],
            'report_cohort_links': [{'link_id': 'L-S01-1', 'report_id': r1, 'study_id': 'S-S01-1',
                                     'cohort_id': 'C-S01-1'}],
            'sample_sets': [{'sample_set_id': 'SS-S01-01', 'report_id': r1, 'time_bin': 'pre_exercise_baseline'}],
            'measurements': [{'measurement_id': 'X1', 'report_id': r1, 'marker_family': 'mucosal_sIgA'},
                             {'measurement_id': 'X2', 'report_id': r1, 'marker_family': 'metabolome_or_lipidome'}],
            'extraction_provenance': [{'report_id': r1, 'extractor_a_b.extractor_B': 'C'}],
        }, {r1: 45}, [{'report_id': r1, 'table': 'cohorts', 'field': 'sport', 'issue_type': 'not_extractable_from_text',
                       'question': 'sport not stated'},
                      {'report_id': r1, 'table': 'cohorts', 'field': 'training_status', 'issue_type': 'definition_ambiguous',
                       'question': 'unclear'}])

        def run(a, b, out):
            ns = argparse.Namespace(a=a, b=b, label_a='B', label_b='C', slot_a='A', slot_b='B', align='auto',
                                    no_slot_pairing=False, out_dir=out)
            run_compare(ns)
            return json.loads((out / 'agreement_summary.json').read_text())

        s = run(files['B'], files['C'], td / 'cmp')
        T = s['tables']
        dis = list(csv.DictReader((td / 'cmp' / 'disagreements.csv').open(encoding='utf-8')))
        emp = list(csv.DictReader((td / 'cmp' / 'empty_by_both.csv').open(encoding='utf-8')))
        mins = list(csv.DictReader((td / 'cmp' / 'minutes_and_questions.csv').open(encoding='utf-8')))
        rep = T['reports']
        check('reports aligned by key on 2 pre-filled rows', rep['align'] == 'key:report_id' and rep['rows_matched'] == 2)
        check('generator pre-filled bibliographic cells are not scored; 3 judgement cells agree',
              rep['agree'] == 3 and 'reports.title' in s['not_scored_columns'])
        check('slot pairing: B slot A vs C slot B counted as agreement',
              not any(d['field'].startswith('screening_decision_reviewer') for d in dis))
        check('wrong-slot entry reported as slot warning',
              any(w['column'] == 'screening_decision_reviewer_A' and w['reviewer'] == 'C' for w in s['slot_warnings']))
        check('multi-valued field compared as a set', not any(d['field'] == 'immune_link' for d in dis))
        check('one-sided cell listed as only_B', any(d['field'] == 'reviewer_notes' and d['category'] == 'only_B' for d in dis))
        coh = T['cohorts']
        check('cohorts: count 12 vs "12" agrees; age_range disagrees',
              coh['agree'] == 2 and coh['disagree'] == 1 and any(d['field'] == 'age_range' and d['value_B'] == '20-30'
                                                                  and d['value_C'] == '21-30' for d in dis))
        check('sample_sets: one row only in B', T['sample_sets']['rows_only_B'] == 1 and T['sample_sets']['rows_matched'] == 1)
        check('measurements: different IDs -> ordinal alignment, 1 agree + 1 disagree on marker_family',
              T['measurements']['align'].startswith('ordinal') and T['measurements']['agree'] >= 1
              and any(d['field'] == 'marker_family' and d['category'] == 'disagree' for d in dis))
        check('provenance aligned by report_id; reviewer-identity columns not scored',
              T['extraction_provenance']['align'] == 'key:report_id' and T['extraction_provenance']['rows_matched'] == 2
              and not any(d['table'] == 'extraction_provenance' for d in dis))
        check('coded+count agreement excludes identifiers and free text',
              T['measurements']['coded_and_counts_only']['agree'] == 1
              and T['measurements']['coded_and_counts_only']['disagree'] == 1)
        check('empty-by-both flagged as not extractable when a reviewer said so',
              any(e['field'] == 'sport' and e['candidate_reason'].startswith('not_extractable') for e in emp))
        check('empty-by-both flagged as unclear for definition_ambiguous',
              any(e['field'] == 'training_status' and e['candidate_reason'].startswith('manual_or_dictionary_unclear')
                  for e in emp))
        check('unflagged empty-by-both left for D', any(e['candidate_reason'].startswith('unflagged') for e in emp))
        check('minutes read per report from README',
              any(m['report_id'] == r1 and m['minutes_B'] == '30' and m['minutes_C'] == '45' for m in mins)
              and any(m['report_id'] == r2 and m['minutes_B'] == '12.5' for m in mins))
        # CSV export path gives identical results
        export(files['B'], td / 'csv_B', schema)
        export(files['C'], td / 'csv_C', schema)
        s2 = run(td / 'csv_B', td / 'csv_C', td / 'cmp_csv')
        check('CSV exports give the same agreement as the workbooks',
              s2['overall'] == s['overall'] and s2['disagreement_categories'] == s['disagreement_categories'])
    passed = sum(r['passed'] for r in results)
    print(json.dumps({'selftest': 'PASS' if ok else 'FAIL', 'passed': passed, 'total': len(results),
                      'failed': [r['check'] for r in results if not r['passed']]}, ensure_ascii=False))
    return 0 if ok else 1


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest='cmd', required=True)
    c = sub.add_parser('compare', help='compare two extraction workbooks / CSV-export directories')
    c.add_argument('--a', type=Path, required=True, help='first reviewer (.xlsx or CSV directory)')
    c.add_argument('--b', type=Path, required=True, help='second reviewer (.xlsx or CSV directory)')
    c.add_argument('--label-a', default='B', help='label of --a (default B: pilot reviewer B)')
    c.add_argument('--label-b', default='C', help='label of --b (default C: pilot reviewer C)')
    c.add_argument('--slot-a', default='A', choices=['A', 'B'], help='slot columns used by --a (default A)')
    c.add_argument('--slot-b', default='B', choices=['A', 'B'], help='slot columns used by --b (default B)')
    c.add_argument('--no-slot-pairing', action='store_true', help='compare *_A with *_A and *_B with *_B')
    c.add_argument('--align', choices=['auto', 'key', 'ordinal'], default='auto')
    c.add_argument('--out-dir', type=Path, required=True)
    e = sub.add_parser('export', help='write one CSV per table (+ pilot_notes, README minutes) for git')
    e.add_argument('--in', dest='inp', type=Path, required=True)
    e.add_argument('--out-dir', type=Path, required=True)
    sub.add_parser('selftest', help='synthetic pair in a temporary directory')
    args = ap.parse_args(argv)
    if args.cmd == 'compare' and args.label_a == args.label_b:
        ap.error('--label-a and --label-b must differ')
    if args.cmd == 'compare':
        return run_compare(args)
    if args.cmd == 'export':
        print(json.dumps({'written': export(args.inp, args.out_dir, load_schema())}, ensure_ascii=False))
        return 0
    return selftest()


if __name__ == '__main__':
    sys.exit(main())
